/* Risk Engine invariance proof — Volatility Sizing Unit phase.

   The Volatility Sizing Unit is an INFORMATIONAL indicator. It must be
   impossible for it to change anything the Risk & Trade Decision Engine
   produces. This suite proves that in the only way that actually counts:
   a byte-exact comparison against a golden snapshot of the risk layer's
   output CAPTURED FROM THE REPOSITORY BEFORE THE INDICATOR EXISTED.

   The snapshot below is not regenerated by this file and is not derived
   from the current code. It was produced by running the pre-change
   assets/js/risk/* modules against a fixed downtrend fixture and the
   real (unmodified) AnalysisEngine, with the two documented
   non-deterministic fields (timestamps, execution timings) scrubbed.

     pre-change SHA-256 : ac7e02b1c89e5db0ab65e41338021f81900c825ef722b5f8b077aaa1e509d163
     pre-change bytes   : 6150

   If any future change alters risk-decision-engine.js, risk-evidence-
   model.js, trade-level-validator.js, any analysis engine they read, or
   the shared candle-utils.js primitives, this suite fails immediately
   and points at the exact scenario that moved.

   The suite runs every scenario TWICE: once with the risk layer alone,
   and once with the Volatility Sizing Unit loaded into the same sandbox
   alongside it. Both must equal the golden snapshot.

   Run: node tests/risk-engine-invariance.test.js */

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const crypto = require('crypto');

let passed = 0, failed = 0;
function assert(cond, msg){ if(cond){ passed++; console.log('  \u2713', msg); } else { failed++; console.error('  \u2717 FAIL:', msg); } }
function section(t){ console.log('\n' + t); }

const GOLDEN_SHA256 = 'ac7e02b1c89e5db0ab65e41338021f81900c825ef722b5f8b077aaa1e509d163';
const GOLDEN = "{\"no-proposal\":{\"version\":1,\"source\":\"RiskDecisionEngine\",\"direction\":\"NONE\",\"proposedDirection\":\"NONE\",\"tradeability\":\"REJECTED\",\"vetoes\":[{\"code\":\"MISSING_TIMEFRAME\",\"severity\":\"HARD\",\"message\":\"No timeframe context supplied.\"}],\"warnings\":[],\"confluence\":[],\"underlyingBias\":null,\"confluenceMode\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"riskDistance\":null,\"aiProposal\":null,\"evaluatedAt\":\"<scrubbed>\",\"candleCount\":180,\"candleRange\":{\"lowestLow\":20943,\"highestHigh\":25004},\"contextGeneratedAt\":\"<scrubbed>\",\"lastCandleTime\":1755461100,\"config\":{\"minRiskReward\":1.5,\"minCandles\":50,\"minConfluenceSupporting\":3,\"maxRiskDistancePct\":null,\"entryZoneTolerancePct\":0.25}},\"valid-short\":{\"version\":1,\"source\":\"RiskDecisionEngine\",\"direction\":\"NONE\",\"proposedDirection\":\"SHORT\",\"tradeability\":\"REJECTED\",\"vetoes\":[{\"code\":\"MISSING_TIMEFRAME\",\"severity\":\"HARD\",\"message\":\"No timeframe context supplied.\"}],\"warnings\":[],\"confluence\":[],\"underlyingBias\":null,\"confluenceMode\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"riskDistance\":null,\"aiProposal\":{\"finalDecision\":\"SELL\",\"direction\":\"SHORT\",\"confidence\":72,\"riskReward\":null},\"evaluatedAt\":\"<scrubbed>\",\"candleCount\":180,\"candleRange\":{\"lowestLow\":20943,\"highestHigh\":25004},\"contextGeneratedAt\":\"<scrubbed>\",\"lastCandleTime\":1755461100,\"config\":{\"minRiskReward\":1.5,\"minCandles\":50,\"minConfluenceSupporting\":3,\"maxRiskDistancePct\":null,\"entryZoneTolerancePct\":0.25}},\"inverted-long\":{\"version\":1,\"source\":\"RiskDecisionEngine\",\"direction\":\"NONE\",\"proposedDirection\":\"LONG\",\"tradeability\":\"REJECTED\",\"vetoes\":[{\"code\":\"MISSING_TIMEFRAME\",\"severity\":\"HARD\",\"message\":\"No timeframe context supplied.\"}],\"warnings\":[],\"confluence\":[],\"underlyingBias\":null,\"confluenceMode\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"riskDistance\":null,\"aiProposal\":{\"finalDecision\":\"BUY\",\"direction\":\"LONG\",\"confidence\":80,\"riskReward\":null},\"evaluatedAt\":\"<scrubbed>\",\"candleCount\":180,\"candleRange\":{\"lowestLow\":20943,\"highestHigh\":25004},\"contextGeneratedAt\":\"<scrubbed>\",\"lastCandleTime\":1755461100,\"config\":{\"minRiskReward\":1.5,\"minCandles\":50,\"minConfluenceSupporting\":3,\"maxRiskDistancePct\":null,\"entryZoneTolerancePct\":0.25}},\"poor-rr\":{\"version\":1,\"source\":\"RiskDecisionEngine\",\"direction\":\"NONE\",\"proposedDirection\":\"SHORT\",\"tradeability\":\"REJECTED\",\"vetoes\":[{\"code\":\"MISSING_TIMEFRAME\",\"severity\":\"HARD\",\"message\":\"No timeframe context supplied.\"}],\"warnings\":[],\"confluence\":[],\"underlyingBias\":null,\"confluenceMode\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"riskDistance\":null,\"aiProposal\":{\"finalDecision\":\"SELL\",\"direction\":\"SHORT\",\"confidence\":60,\"riskReward\":null},\"evaluatedAt\":\"<scrubbed>\",\"candleCount\":180,\"candleRange\":{\"lowestLow\":20943,\"highestHigh\":25004},\"contextGeneratedAt\":\"<scrubbed>\",\"lastCandleTime\":1755461100,\"config\":{\"minRiskReward\":1.5,\"minCandles\":50,\"minConfluenceSupporting\":3,\"maxRiskDistancePct\":null,\"entryZoneTolerancePct\":0.25}},\"decision-only\":{\"version\":1,\"source\":\"RiskDecisionEngine\",\"direction\":\"NONE\",\"proposedDirection\":\"NONE\",\"tradeability\":\"REJECTED\",\"vetoes\":[{\"code\":\"MISSING_TIMEFRAME\",\"severity\":\"HARD\",\"message\":\"No timeframe context supplied.\"}],\"warnings\":[],\"confluence\":[],\"underlyingBias\":null,\"confluenceMode\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"riskDistance\":null,\"aiProposal\":{\"finalDecision\":\"WAIT\",\"direction\":null,\"confidence\":40,\"riskReward\":null},\"evaluatedAt\":\"<scrubbed>\",\"candleCount\":180,\"candleRange\":{\"lowestLow\":20943,\"highestHigh\":25004},\"contextGeneratedAt\":\"<scrubbed>\",\"lastCandleTime\":1755461100,\"config\":{\"minRiskReward\":1.5,\"minCandles\":50,\"minConfluenceSupporting\":3,\"maxRiskDistancePct\":null,\"entryZoneTolerancePct\":0.25}},\"evidence-BIAS\":{\"version\":1,\"direction\":\"NONE\",\"mode\":\"BIAS\",\"confluence\":[{\"source\":\"trend\",\"stance\":\"BEARISH\",\"detail\":\"Primary trend is bearish.\"},{\"source\":\"marketStructure\",\"stance\":\"BEARISH\",\"detail\":\"Most recent structure event is a bearish BOS at 21379.\"},{\"source\":\"liquidity\",\"stance\":\"NEUTRAL\",\"detail\":\"17 liquidity pool(s) resting, none swept yet.\"},{\"source\":\"orderBlocks\",\"stance\":\"MISSING\",\"detail\":\"No unmitigated order blocks.\"},{\"source\":\"fairValueGaps\",\"stance\":\"BEARISH\",\"detail\":\"54 bullish and 89 bearish unfilled fair value gaps.\"},{\"source\":\"premiumDiscount\",\"stance\":\"BULLISH\",\"detail\":\"Price is in the discount half of the dealing range.\"},{\"source\":\"supportResistance\",\"stance\":\"NEUTRAL\",\"detail\":\"Nearest level ahead is support at 21379.\"},{\"source\":\"volume\",\"stance\":\"NEUTRAL\",\"detail\":\"Volume data available; not treated as directional evidence.\"}],\"supportingCount\":0,\"conflictingCount\":0,\"neutralCount\":3,\"missingCount\":1,\"bullishCount\":1,\"bearishCount\":3,\"underlyingBias\":\"BEARISH\",\"contextAvailable\":true},\"evidence-SHORT\":{\"version\":1,\"direction\":\"SHORT\",\"mode\":\"DIRECTIONAL\",\"confluence\":[{\"source\":\"trend\",\"stance\":\"SUPPORTING\",\"detail\":\"Primary trend is bearish.\"},{\"source\":\"marketStructure\",\"stance\":\"SUPPORTING\",\"detail\":\"Most recent structure event is a bearish BOS at 21379.\"},{\"source\":\"liquidity\",\"stance\":\"NEUTRAL\",\"detail\":\"17 liquidity pool(s) resting, none swept yet.\"},{\"source\":\"orderBlocks\",\"stance\":\"MISSING\",\"detail\":\"No unmitigated order blocks.\"},{\"source\":\"fairValueGaps\",\"stance\":\"SUPPORTING\",\"detail\":\"54 bullish and 89 bearish unfilled fair value gaps.\"},{\"source\":\"premiumDiscount\",\"stance\":\"CONFLICTING\",\"detail\":\"Price is in the discount half of the dealing range.\"},{\"source\":\"supportResistance\",\"stance\":\"CONFLICTING\",\"detail\":\"Nearest level ahead is support at 20943.\"},{\"source\":\"volume\",\"stance\":\"NEUTRAL\",\"detail\":\"Volume data available; not treated as directional evidence.\"}],\"supportingCount\":3,\"conflictingCount\":2,\"neutralCount\":2,\"missingCount\":1,\"bullishCount\":0,\"bearishCount\":0,\"underlyingBias\":null,\"contextAvailable\":true},\"validator-short\":{\"valid\":false,\"direction\":\"NONE\",\"vetoes\":[{\"code\":\"INVALID_DIRECTION\",\"severity\":\"HARD\",\"message\":\"Direction must be 'bullish' or 'bearish'; received \\\"SHORT\\\".\"}],\"warnings\":[],\"riskDistance\":null,\"rewardDistance\":null,\"calculatedRiskReward\":null,\"aiStatedRiskReward\":null,\"targetCount\":0}}";

function load(files){
  const sandbox = { console: { log(){}, warn(){}, error(){}, info(){} }, Date, Math, JSON, Number, Array, Object, String, isNaN };
  sandbox.window = sandbox;
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);
  files.forEach(f => vm.runInContext(fs.readFileSync(path.join(__dirname, '..', f), 'utf8'), sandbox));
  return sandbox;
}

const ANALYSIS_FILES = [
  'assets/js/analysis/candle-utils.js',
  'assets/js/analysis/market-structure-engine.js',
  'assets/js/analysis/liquidity-engine.js',
  'assets/js/analysis/order-block-engine.js',
  'assets/js/analysis/fvg-engine.js',
  'assets/js/analysis/premium-discount-engine.js',
  'assets/js/analysis/volume-engine.js',
  'assets/js/analysis/trend-engine.js',
  'assets/js/analysis/support-resistance-engine.js',
  'assets/js/analysis/analysis-engine.js'
];
const RISK_FILES = [
  'assets/js/risk/trade-level-validator.js',
  'assets/js/risk/risk-evidence-model.js',
  'assets/js/risk/risk-decision-engine.js'
];
const LAB_FILES = ['assets/js/lab/volatility-sizing-unit.js'];

/* The identical fixture the golden snapshot was captured from. */
function fixtureCandles(){
  const out = [];
  let t = 1755300000, px = 25000;
  for(let leg = 0; leg < 9; leg++){
    for(let i = 0; i < 12; i++){
      const o = px, c = +(px - 38 - (i % 3) * 9).toFixed(2);
      out.push({ time: t, open: o, high: +(o + 4).toFixed(2), low: +(c - 4).toFixed(2), close: c, volume: 220000 + i * 4000 });
      px = c; t += 900;
    }
    for(let i = 0; i < 8; i++){
      const o = px, c = +(px + 16).toFixed(2);
      out.push({ time: t, open: o, high: +(c + 5).toFixed(2), low: +(o - 5).toFixed(2), close: c, volume: 90000 + i * 2000 });
      px = c; t += 900;
    }
  }
  return out;
}

function scrub(v){
  return JSON.parse(JSON.stringify(v, (k, val) => {
    if(k === 'executionTimeMs' || k === 'generatedAt' || k === 'contextGeneratedAt' || k === 'evaluatedAt' || k === 'at') return '<scrubbed>';
    return val;
  }));
}

/** Reproduces the snapshot from whatever code is on disk right now. */
function buildSnapshot(withLab){
  const files = withLab ? ANALYSIS_FILES.concat(RISK_FILES, LAB_FILES) : ANALYSIS_FILES.concat(RISK_FILES);
  const sb = load(files);
  const AnalysisEngine = sb.window.DannyChart.Analysis.AnalysisEngine;
  const Risk = sb.window.DannyChart.Risk;

  const candles = fixtureCandles();
  const ctx = AnalysisEngine.analyze(candles, { symbol: 'NIFTY', timeframe: '15' });
  const last = candles[candles.length - 1].close;

  /* With the lab module present, exercise it BEFORE the risk calls —
     if it could contaminate anything (shared globals, a mutated candle
     array, a patched prototype), the risk output below would move. */
  if(withLab){
    const VSU = sb.window.DannyChart.Lab.VolatilitySizingUnit;
    VSU.analyze(candles, {});
    VSU.analyze(candles, { atrPeriod: 20, percentileLookback: 100 });
  }

  const PROPOSALS = [
    { name: 'no-proposal', input: {} },
    { name: 'valid-short', input: { tradeLevels: { direction: 'SHORT', entry: last, stopLoss: last + 60, targets: [last - 120, last - 240] }, decision: { finalDecision: 'SELL', confidence: 72 } } },
    { name: 'inverted-long', input: { tradeLevels: { direction: 'LONG', entry: last, stopLoss: last + 50, targets: [last + 100] }, decision: { finalDecision: 'BUY', confidence: 80 } } },
    { name: 'poor-rr', input: { tradeLevels: { direction: 'SHORT', entry: last, stopLoss: last + 100, targets: [last - 50] }, decision: { finalDecision: 'SELL', confidence: 60 } } },
    { name: 'decision-only', input: { decision: { finalDecision: 'WAIT', confidence: 40 } } }
  ];

  const snapshot = {};
  PROPOSALS.forEach(p => {
    snapshot[p.name] = scrub(Risk.RiskDecisionEngine.evaluate(
      Object.assign({ candles, analysisContext: ctx, currentPrice: last }, p.input)
    ));
  });
  snapshot['evidence-BIAS'] = scrub(Risk.RiskEvidenceModel.evaluate(ctx, { direction: 'NONE', currentPrice: last }));
  snapshot['evidence-SHORT'] = scrub(Risk.RiskEvidenceModel.evaluate(ctx, { direction: 'SHORT', currentPrice: last }));
  snapshot['validator-short'] = scrub(Risk.TradeLevelValidator.validate(
    { direction: 'SHORT', entry: last, stopLoss: last + 60, targets: [last - 120, last - 240] },
    { currentPrice: last }
  ));
  return JSON.stringify(snapshot);
}

section('1. The golden snapshot itself');
{
  const sha = crypto.createHash('sha256').update(GOLDEN).digest('hex');
  assert(sha === GOLDEN_SHA256, 'the embedded pre-change snapshot still hashes to its recorded SHA-256');
  assert(GOLDEN.length === 6150, 'and is still its recorded length (6150 bytes)');
}

section('2. Risk layer WITHOUT the Volatility Sizing Unit loaded');
{
  const now = buildSnapshot(false);
  assert(now === GOLDEN, 'every risk output is byte-identical to the pre-change capture');
  if(now !== GOLDEN){
    const a = JSON.parse(now), b = JSON.parse(GOLDEN);
    Object.keys(b).forEach(k => {
      if(JSON.stringify(a[k]) !== JSON.stringify(b[k])) console.error('    scenario that moved:', k);
    });
  }
}

section('3. Risk layer WITH the Volatility Sizing Unit loaded and exercised');
{
  const now = buildSnapshot(true);
  assert(now === GOLDEN, 'loading and running the indicator changes nothing in the risk layer');
}

section('4. The indicator cannot reach the risk layer at all');
{
  const sb = load(LAB_FILES.concat(['assets/js/analysis/candle-utils.js']));
  assert(!sb.window.DannyChart.Risk, 'loading the indicator alone does not create window.DannyChart.Risk');
  assert(!!sb.window.DannyChart.Lab && !!sb.window.DannyChart.Lab.VolatilitySizingUnit,
    'it registers only under window.DannyChart.Lab');
  const keys = Object.keys(sb.window.DannyChart);
  assert(keys.every(k => k === 'Lab' || k === 'Analysis'),
    'and touches no other DannyChart namespace (present: ' + keys.join(', ') + ')');
}

section('5. Protected and decision-owning files are untouched by this phase');
{
  const MUST_NOT_MENTION_LAB = [
    'assets/js/risk/risk-decision-engine.js',
    'assets/js/risk/risk-evidence-model.js',
    'assets/js/risk/trade-level-validator.js',
    'assets/js/analysis/analysis-engine.js',
    'assets/js/analysis/candle-utils.js',
    'assets/js/analysis/market-structure-engine.js',
    'assets/js/analysis/liquidity-engine.js',
    'assets/js/analysis/order-block-engine.js',
    'assets/js/analysis/fvg-engine.js',
    'assets/js/analysis/premium-discount-engine.js',
    'assets/js/analysis/volume-engine.js',
    'assets/js/analysis/trend-engine.js',
    'assets/js/analysis/support-resistance-engine.js',
    'assets/js/chart/annotation-model.js',
    'assets/js/chart/chart-renderer.js',
    'assets/js/chart/decision-panel.js',
    'assets/js/chart/analysis-context-adapter.js'
  ];
  MUST_NOT_MENTION_LAB.forEach(f => {
    const src = fs.readFileSync(path.join(__dirname, '..', f), 'utf8');
    assert(!/VolatilitySizingUnit|DannyChart\.Lab|volatility-sizing-unit/.test(src),
      f + ' contains no reference to the new indicator');
  });
}

console.log(`\n==== RESULT: ${passed} passed, ${failed} failed ====`);
if(failed > 0) process.exitCode = 1;
